### ISSUE TITLE
400 Client Error

### ISSUE THREAD

**Issue by cqnimin** [tavily-ai/tavily-python#15]
i apply a new key, add try to run the sample code, but it is always fail.

from tavily import TavilyClient
tavily = TavilyClient(api_key="***")
# For basic search:
response = tavily.search(query="Should I invest in Apple in 2024?")

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[<ipython-input-12-6e24e997be2c>](https://localhost:8080/#) in <cell line: 4>()
      2 tavily = TavilyClient(api_key="tavily-cosQzSSIbve8T1DbjnmMY39vD0l3wXvQ")
      3 # For basic search:
----> 4 response = tavily.search(query="Should I invest in Apple in 2024?")

2 frames
[/usr/local/lib/python3.10/dist-packages/requests/models.py](https://localhost:8080/#) in raise_for_status(self)
   1019 
   1020         if http_error_msg:
-> 1021             raise HTTPError(http_error_msg, response=self)
   1022 
   1023     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://api.tavily.com/search

**Comment by DrRaja** [comment]
Same problem here. I was using the API and it used to give intermittent 502 errors, but since a couple of days all requests end with a 400 Client Error.

**Comment by carl-vbn** [comment]
Hello,
Are you still experiencing the issue? If so, please regenerate your API key on the [Tavily platform ](https://app.tavily.com/home)and try again.
Also, be careful when posting error messages that you don't accidentally reveal your API key.

**Comment by jobic10** [comment]
> i apply a new key, add try to run the sample code, but it is always fail.
> 
> from tavily import TavilyClient tavily = TavilyClient(api_key="***")
> 
> # For basic search:
> response = tavily.search(query="Should I invest in Apple in 2024?")
> 
> HTTPError Traceback (most recent call last) in <cell line: 4>() 2 tavily = TavilyClient(api_key="tavily-cosQzSSIbve8T1DbjnmMY39vD0l3wXvQ") 3 # For basic search: ----> 4 response = tavily.search(query="Should I invest in Apple in 2024?")
> 
> 2 frames [/usr/local/lib/python3.10/dist-packages/requests/models.py](https://localhost:8080/#) in raise_for_status(self) 1019 1020 if http_error_msg: -> 1021 raise HTTPError(http_error_msg, response=self) 1022 1023 def close(self):
> 
> HTTPError: 400 Client Error: Bad Request for url: https://api.tavily.com/search

Avoid exposing your API keys
