### ISSUE TITLE
[question] Using Tavily API with open AI Azure end point ?

### ISSUE THREAD

**Issue by timtensor** [tavily-ai/tavily-python#18]
Hello i recently came to know about tavily api and was curious to know if it could be used together with open ai azure endpoint ? If so how ? 
The idea behind is that we want to 
a) do a query using prompt template 
b) Request a step by step query for example a) Find company A b) Where is the company located c) How many employees are present  . Is there a possibility to do such a sequential querying ? 

Those are the questions from us  . Looking forward to hear from you .

**Comment by carl-vbn** [comment]
Hello,
It is definitely possible to make multiple successive searches. However, the API is currently not able to provide you with relevant prompts, as it is designed to answer questions, not ask them. That being said, we are constantly working on improving our feature set and a "follow up questions" functionality is on the radar..
