### ISSUE TITLE
Bug : Search Method Fails with Multiple Domains 

### ISSUE THREAD

**Issue by a-ayari03** [tavily-ai/tavily-python#21]
Hi tavily team !
When using the tavily.search method with a single domain name, the search functionality works correctly and returns the expected results. However, when including multiple domain names in the include_domains parameter, the search results are null (no results are returned).

Example Code:

```python
# Single domain search - works correctly
response_1 = tavily.search(
    query="Qu'elle est la dernière nouveauté du 25 Juin 2024 ?",
    search_depth="advanced",
    include_domains=['www.allocine.fr'],
    include_raw_content=True
)
print(response_1)  # Expected: Non-null results
#{'query': "Qu'elle est la dernière nouveauté du 25 Juin 2024 ?",
 #'follow_up_questions': None,
 #'answer': None,
 #'images': None,
#'results': [{'{'title': 'Netflix : 17 nouveaux films à voir en juin 2024, dont le film de ...',
#}

# Multiple domain search - returns null results
response_2 = tavily.search(
    query="Qu'elle est la dernière nouveauté du 25 Juin 2024 ?",
    search_depth="advanced",
    include_domains = ['www.allocine.fr', 'www.programme.tv'],
    include_raw_content=True
)
print(response_2)  # Unexpected: Null results

#{'query': "Qu'elle est la dernière nouveauté du 25 Juin 2024 ?",
# 'follow_up_questions': None,
# 'answer': None,
# 'images': None,
# 'results': [],
# 'response_time': 1.21}
``` 
Expected Behavior:
When multiple domain names are included in the include_domains parameter, the search should return relevant results from the specified domains.

Actual Behavior:
The search method returns null results when multiple domain names are included.

Environment:

    tavily-python version: [0.3.3]
    Python version: [3.10.0]
    Operating System: [Windows 11]

Thank you so much for you time :)

**Comment by abhishek-fluidai** [comment]
Facing the same issue in the API, through it works fine on the UI

**Comment by abhishek-fluidai** [comment]
Hi I found a solution to that.
Just add a **space** in before each domain.
include_domains = [
' www.allocine.fr', 
' www.programme.tv'
],

**Comment by beschmitt** [comment]
Adding a space in front of each domain works for whatever reason. Would be good to get a more official solution.
Also I'd love it if the included domains were more of a "look through these domains first" instead of "only look through these domains".

**Comment by MayRamati** [comment]
Hello,
We're looking into this issue and will let you know the status as soon as we have more information. Thanks for your patience!

**Comment by adelaharpe** [comment]
I have the same issue but with the AsyncTavilyClient. The addition of space before doesn't solve the issue on my side.

**Comment by MayRamati** [comment]
Hi there,

We'd like to inform you that the issue with the include_domains parameter has been resolved. The API now functions as expected when using multiple domain names.
