### ISSUE TITLE
Request: JavaScript Wrapper for Tavily Search API

### ISSUE THREAD

**Issue by AsharibAli** [tavily-ai/tavily-python#24]
**Dear Tavily Team,**

Please consider creating a JavaScript wrapper `tavily-js` for your Tavily Search API. While the existing Python wrapper is fantastic, a JavaScript version would greatly benefit the JS developer community, making it easier to integrate and use your API in **JavaScript/TypeScript** projects.

Thank you for your attention to this request.

Sincerely, 
Asharib Ali

**Comment by MayRamati** [comment]
Hello,

We’re happy to let you know that we already have a JavaScript SDK available. It provides seamless interaction with the Tavily Search API, enabling you to leverage our search and extract functionalities directly within JavaScript and TypeScript applications. You can find the detailed documentation and get started here: [Tavily JavaScript SDK Documentation](https://docs.tavily.com/docs/javascript-sdk/tavily-search/getting-started).

Additionally, we invite you to join our [Community](https://community.tavily.com/) for the latest updates, feature announcements, and to connect with other developers building with Tavily.

**Comment by AsharibAli** [comment]
Sounds amazing! thanks
