### ISSUE TITLE
Pymongo is not included as a dependency  `0.3.8`

### ISSUE THREAD

**Issue by jdcaballerov** [tavily-ai/tavily-python#32]
Importing tavily causes the following import chain:

`tavily/__init__.py`

```
from .hybrid_rag import TavilyHybridClient
from pymongo.collection import Collection
```

pymongo is not included as a dependency.

**Comment by carl-vbn** [comment]
Thank you for reporting this issue. It was just used for typing, so we decided to remove it to avoid having to add a dependency. 
The change has been published under version 0.3.9 on pip.
