### ISSUE TITLE
Questions about Tavily API and client

### ISSUE THREAD

**Issue by bukosabino** [tavily-ai/tavily-python#4]
Hi all,

I have some questions related to tavily API search:

- Is there a semantic or keyword search engine?
- What is the price of the API? Right now I am using the 1k free queries.
- Could I filter the search space? not only using domains, but also directly a list of urls?
- Is there a way to do asynchronous API calls?

**Comment by assafelovic** [comment]
Hey @bukosabino thanks for reaching out!
- Yes, this is exactly the basis of Tavily search API. It performs a semantic search behind the scenes to find the most relevant online sources for your query. We are currently working on adding keywords as well.
- Please reach out to us at support@tavily.com and we'd be happy to increase your limit. We're currently not monetizing or pricing our API, but mostly focused on learning from our users and improve our product and services.
- Can you please explain more? Not sure what you mean by a list of urls. Generally you can pass a list of urls as a string to "include_domains" param in the API request to whitelist the search only for that use case.
- Of course! But that doesn't relate to the API. You can simply trigger async calls using best practices with any of your preferred language (Node/Python/etc). 

Generally feel free to learn more here: https://docs.tavily.com/docs/tavily-api/rest_api
